export const AGENT_PREMADE_BEHAVIOR_SCHEMES = [
  "mainline_quester",
  "farmer",
  "boss_hunter",
  "looter",
  "completionist",
  "social",
  "survivor",
  "healer",
  "tank",
  "dps",
  "support",
  "grouper",
  "lone_wolf",
  "jump_around",
  "wanderer",
  "training_dummies",
  "dummy_dps",
] as const;
