import {
  COMBAT,
  EMOTES,
  EQUIPMENT_SLOTS,
  FISHING_AGENT_BUNDLE_MULTIPLIER,
  FISHING_AGENT_CATCH_CHANCE_MULTIPLIER,
  FISHING_AGENT_NFT_CHANCE_MULTIPLIER,
  FISHING_AGENT_RARE_CHANCE_MULTIPLIER,
  FISHING_BITE_MAX_MS,
  FISHING_BITE_MIN_MS,
  FISHING_BITE_WINDOW_MS,
  FISHING_CAST_MS,
  FISHING_CHUM_ITEM_ID,
  FISHING_NFT_POND_DEFAULT_CATCH_CHANCE_BPS,
  FISHING_NFT_POND_DEFAULT_GLOBAL_DAILY_CAP,
  FISHING_NFT_POND_DEFAULT_WALLET_DAILY_CAP,
  FISHING_NFT_POND_ERC1155_CATCH_AMOUNT,
  FISHING_NFT_POND_RANDOMNESS_NOTE,
  FISHING_NFT_POND_V1_DECISIONS,
  FISHING_POND_STATUS_NPC_ID,
  FISHING_SELLABLE_ITEM_IDS,
  FISHING_TUTOR_NPC_ID,
  FISHING_VENDOR_NPC_ID,
  FISHING_ZONE,
  FISHING_ZONE_ID,
  ITEMS,
  MINT_CLUB_BASE_SEPOLIA_BOND_ADDRESS,
  MINT_CLUB_BASE_SEPOLIA_CHAIN_ID,
  MINT_CLUB_BASE_SEPOLIA_ERC1155_ADDRESS,
  MINT_CLUB_BASE_SEPOLIA_WETH_ADDRESS,
  MINT_CLUB_DEFAULT_SELL_ROYALTY_BPS,
  MINT_CLUB_REDEMPTION_NPC_ID,
  ONCHAIN_FISHING_ROD_DEFAULT_LABEL,
  ONCHAIN_FISHING_ROD_MFERGPT_AMOUNT_LABEL,
  ONCHAIN_FISHING_ROD_MFERGPT_AMOUNT_WEI,
  AGENT_TRASH_VENDOR_ITEMS_PER_POINT,
  POTION_SHOP_ITEM_IDS,
  POTION_SHOP_NPC_ID,
  POTION_SHOP_PRODUCT_ID,
  POTION_SHOP_PURCHASE_QUANTITIES,
  PROGRESSION,
  QUESTS,
  RESPEC_MFER_NPC_ID,
  SEASON_0_DAILY_POINT_CAP,
  SEASON_0_ID,
  SEASON_0_REFERRAL_ACTIVATION_POINTS,
  SEASON_0_REFERRAL_BONUS_DENOMINATOR,
  SEASON_0_REFERRAL_BONUS_NUMERATOR,
  SEASON_0_REFERRAL_MAX_BONUS_POINTS,
  SEASON_0_REFERRAL_MAX_REFEREES,
  SEASON_0_TOTAL_POINT_CAP,
  TALENT_RESPEC_MFERGPT_AMOUNT_LABEL,
  TALENT_RESPEC_MFERGPT_AMOUNT_WEI,
  TALENT_RESPEC_PRODUCT_ID,
  TRASH_VENDOR_ITEM_IDS,
  TRASH_VENDOR_NPC_ID,
  MFER_APPEARANCE_TRAIT_CATEGORIES,
  AGENT_MFER_APPEARANCE_BLOCKED_TRAITS,
  AGENT_MFER_APPEARANCE_FORCED_TRAITS,
  AGENT_MFER_APPEARANCE_SELECTION_GUIDANCE,
  TRAIT_CHANGE_BASE_CHAIN_ID,
  TRAIT_CHANGE_BASE_RPC_URL,
  TRAIT_CHANGE_BURN_ADDRESS,
  TRAIT_CHANGE_MFERGPT_TOKEN_ADDRESS,
  DEFAULT_MFERGPT_SWAP_ETH_AMOUNT,
  DEFAULT_MFERGPT_SWAP_SLIPPAGE_BPS,
  MFERGPT_BASE_UNISWAP_UNIVERSAL_ROUTER_ADDRESS,
  MFERGPT_BASE_UNISWAP_V4_POOL,
  MFERGPT_BASE_WETH_ADDRESS,
  TALENTS,
  TALENT_TREES,
  WORLD_HUBS,
  WORLD_LANDMARKS,
  WORLD_ROADS,
  getFishingSupplyPrice,
  getFishingRequiredBundleSize,
  getFishingSaleRule,
  getFishingSellAwardPoints,
  getPotionShopPrice,
  getTrashVendorSellValue,
  type PotionShopItemId,
  type PotionShopPurchaseQuantity,
} from "@mferland/shared";
import {
  AGENT_SEASON0_MFERGPT_MIN_BALANCE_LABEL,
  DEFAULT_AGENT_SEASON0_MFERGPT_MIN_BALANCE_WEI,
} from "./agentMferGptGate.js";
import { AGENT_PREMADE_BEHAVIOR_SCHEMES } from "./agentHarnessOptions.js";
import { readAgentSeason0PointMultiplier } from "./agentRewards.js";

export function buildAgentCatalog() {
  return {
    ok: true,
    version: 2,
    generatedAt: new Date().toISOString(),
    endpoints: {
      walletAuthChallenge: "/wallet-auth-challenge",
      agentSession: "/agent-session",
      agentCatalog: "/agent-catalog",
      seasonLeaderboard: "/season/leaderboard",
      seasonReferrals: "/season/referrals?wallet={walletAddress}",
    },
    walletIdentity: {
      registeredClientKinds: ["human", "agent"],
      invariant: "A wallet registers as either human or agent. Human wallets cannot mint agent sessions or join as declared agents, and agent wallets cannot join as human players.",
      agentSessionMismatch: {
        code: "agent_wallet_registration_mismatch",
        recovery: "use_agent_registered_wallet",
      },
      profileFields: ["registeredClientKind"],
    },
    season0: {
      id: SEASON_0_ID,
      dailyPointCap: SEASON_0_DAILY_POINT_CAP,
      totalPointCap: SEASON_0_TOTAL_POINT_CAP,
      pointSources: {
        eligibleBaseSources: ["quest", "event"],
        excludedBonusSources: ["referral", "manual"],
        note: "Referral bonuses only use human base Season 0 points after normal caps apply. Referral events never cascade into more referral bonuses.",
      },
      referrals: {
        humanOnly: true,
        agentsEligible: false,
        inviteUrl: "https://game.mfergpt.lol/?referral=<referrer-wallet>",
        queryParam: "referral",
        bindTiming: "first wallet character creation only",
        activationPoints: SEASON_0_REFERRAL_ACTIVATION_POINTS,
        activationNote: "Referrals are active immediately. Eligible human base points accrue across sessions from the first quest or event award.",
        bonusRatePercent: (SEASON_0_REFERRAL_BONUS_NUMERATOR / SEASON_0_REFERRAL_BONUS_DENOMINATOR) * 100,
        maxBonusPointsPerReferralSide: SEASON_0_REFERRAL_MAX_BONUS_POINTS,
        maxRefereesPerReferrer: SEASON_0_REFERRAL_MAX_REFEREES,
        referrerCanRemove: true,
        removalNote: "Human referrers can remove a referral from the character Referrals tab. This deletes referral bonus points for both wallets and frees the slot; base Season 0 points stay intact.",
        noCascade: true,
        endpoints: {
          summary: "/season/referrals?wallet={walletAddress}",
          leaderboard: "/season/leaderboard",
        },
      },
    },
    controls: {
      session: ["leave"],
      movement: ["input", "respawn"],
      social: ["chat", "emote", "agentStatus", "shareQuestLink"],
      npc: ["interact"],
      quests: ["acceptQuest", "completeQuest", "cancelQuest"],
      selection: ["selectTarget", "selectSelfTarget"],
      combat: ["combatAction"],
      lootAndItems: ["lootCorpse", "equipItem", "unequipItem", "useItem", "sellTrashItems", "startFishing", "reelFishing", "cancelFishing", "submitFishingNftClaimTx", "abandonFishingNftCatch", "submitMintClubRedemptionTx", "refreshFishingNftHistory", "sellFishingItems", "purchaseFishingSupply", "purchaseOnchainFishingRod"],
      character: ["selectTalent", "updateTraits", "respecTalents", "removeSeasonReferral"],
      walletStores: ["purchasePotionShopItem", "purchaseFishingSupply", "respecTalents", "registerChainGear"],
      walletActions: [
        "connectWallet",
        "refreshWalletBalances",
        "quoteMferGptSwap",
        "swapEthForMferGpt",
        "buyGearWithEth",
        "buyGearWithMfer",
        "buyGearWithMferGpt",
        "mintSeasonPassWithEth",
        "mintSeasonPassWithMfer",
        "mintSeasonPassWithMferGpt",
        "claimFishingPondNft",
        "sellMintClubPondNft",
        "burnMferGptForPaymentProof",
      ],
      localClientPreferences: [
        "setHotbarSlot",
        "setQuestFocus",
        "toggleCompletedQuestVisibility",
        "setGraphicsQuality",
        "setAudio",
        "setNameplates",
        "configureLocalCryptoContracts",
      ],
    },
    agentHarness: {
      bridgeEndpoints: {
        start: "/agent-start",
        observe: "/agent-observe",
        action: "/agent-action",
        command: "/agent-command",
        commandStop: "/agent-command-stop",
        fishingTool: "/agent-fishing",
        stop: "/agent-stop",
      },
      readOnlyEndpoints: {
        profile: "/agent-profile?wallet=0x...",
        world: "/agent-world",
        playerByWallet: "/agent-player?wallet=0x...",
        playerByName: "/agent-player?name=...",
        milestones: "/agent-milestones?questId=baron-of-static",
        livePlayerFields: ["agentStatus", "agentCommand", "lastAgentActivityAgoMs", "currentQuest", "questCounts", "equipment", "activeCast"],
        note: "Use these GET endpoints for saved character facts and public live world state before starting a bridge session. /agent-world and /agent-player include public agent status and autoplay command/playtime fields for online agents.",
      },
      commands: {
        kinds: ["finish_next_quest", "finish_quest", "play_for", "farm_until", "run_goals"],
        stopWhen: ["any", "all"],
        profile: {
          priorities: ["auto", "quester", "farmer", "boss_hunter", "looter", "completionist", "social"],
          roles: ["auto", "tank", "healer", "dps", "support"],
          specs: ["auto", "brawler_tank", "brawler_dps", "caster_fire", "caster_frost", "utility_ranger", "utility_support"],
          partyModes: ["auto", "grouper", "lone_wolf", "follow_leader"],
          risks: ["safe", "normal", "bold"],
          social: ["quiet", "normal", "chatty"],
        },
        premadeSchemes: [...AGENT_PREMADE_BEHAVIOR_SCHEMES],
        premadeSchemeNote: "behaviorScheme selects a premade profile seed. Explicit profile fields still override priority, role, spec, partyMode, risk, and social.",
        fishingCommandNote: "Fishing is not farming. Use the dedicated /agent-fishing tool for hosted pond fishing, NFT claim handoffs, fish sales, and fishing-sale prerequisite recovery. operation=sell_fish sells regular offchain fish only after lost-fishing-shoes; poll operation=sell_fish_status with the returned requestId when a sale is still in progress. On prerequisite_required, follow nextRequest with questId=lost-fishing-shoes on /agent-fishing, allow its catalog-declared fishing prerequisites, and never launch /agent-command or generic play_for. The generic /agent-command path with command=play_for and behaviorScheme=fishing remains available only for callers that explicitly chose general autoplay. Use /agent-action action=fish only for an explicitly requested single manual fish loop.",
        goals: {
          types: ["quest_completed", "quest_ready", "quest_accepted", "inventory_at_least", "level_at_least", "xp_gained", "survive_seconds", "arrive_at_landmark", "near_player_count"],
          note: "run_goals requires structured goals; freeform player requests should be translated by the agent before calling /agent-command.",
        },
        constraints: {
          fields: ["noWalletActions", "noPaidActions", "maxDeaths", "maxSafetyStops", "allowedActions", "disallowedActions"],
          defaults: { maxDeaths: null, maxSafetyStops: null },
          walletSigningDefault: false,
          note: "Hosted autoplay cannot sign wallet transactions. Use noWalletActions/noPaidActions when a player request must not spend or request wallet approval. By default deaths and safety retreats are reported but do not end the command; set maxDeaths or maxSafetyStops to 0 for a zero-failure run, or to a positive number for a hard cap.",
        },
        controller: {
          types: ["premade", "external_policy"],
          note: "external_policy is metadata only. Custom agent code runs in the caller-owned harness and calls /agent-action or structured /agent-command; the hosted server does not execute code.",
        },
        maxCommandSeconds: 30 * 60,
        timeboxingNote: "Command time limits are safety guards and budget caps. Success conditions such as quest completion or inventory target still end runs early. A time_limit result disconnects the room bridge automatically while preserving the command result for polling and recap.",
        authNote: "Command endpoints require the same wallet-bound agent session bearer token as observe/action.",
        responseFields: ["status", "summary", "result", "goals", "goalProgress", "questChanges", "inventoryChanges", "equipmentChanges", "finalState", "actionReports", "budget", "usage", "social", "combat", "fishing", "bridge", "postCommand", "prerequisiteRequired"],
        socialRecapNote: "Command results include nearby players/agents seen during the run and recent public chat so agents can report alive-world context to users.",
        fishingRecapNote: "Command results include fishing reel totals, named regular catches, fish vendor sales and points, NFT catch names/status, pending wallet-action count, current wallet/global NFT daily remaining values, and reset timestamp when the pond is configured.",
        sandbox: {
          hostedCodeExecution: false,
          codeRule: "Do not send raw code to hosted /agent-command. Agent-authored behavior code runs in the caller's external policy runner and may call /agent-action directly or request structured autoplay.",
          externalPolicyMetadata: ["controller.type=external_policy", "controller.policyRef", "controller.policyHash"],
        },
      },
      registeredTools: {
        manifests: [
          "/.well-known/ai-tool/mfertown-agent-command.json",
          "/.well-known/ai-tool/mfertown-fishing.json",
          "/.well-known/ai-tool/mfertown-mfergpt-swap.json",
        ],
        fishing: "/agent-fishing",
        swapQuote: "/agent-mfergpt-swap-quote",
        swapResult: "/agent-mfergpt-swap-result",
        xPaymentNote: "Registered tools use an ERC-8257-style manifest and accept zero-value EIP-3009 X-Payment payloads for OpenSea usage reporting.",
      },
    },
    menus: {
      character: {
        observes: ["walletAddress", "season0Points", "season0DailyPoints", "seasonPassOwnership", "referrals", "level", "xp", "stats", "equipment"],
        controls: ["selectSelfTarget", "unequipItem", "refreshSeasonPassOwnership", "removeSeasonReferral"],
      },
      stash: {
        observes: ["inventory", "itemDefinitions", "equipmentComparisons", "consumableDefinitions"],
        controls: ["equipItem", "useItem", "setHotbarSlot"],
      },
      moves: {
        observes: ["combatActions", "talents", "talentTrees", "talentPoints"],
        controls: ["combatAction", "selectTalent", "setHotbarSlot"],
      },
      fishing: {
        tutorNpcId: FISHING_TUTOR_NPC_ID,
        vendorNpcId: FISHING_VENDOR_NPC_ID,
        statusNpcId: FISHING_POND_STATUS_NPC_ID,
        redemptionNpcId: MINT_CLUB_REDEMPTION_NPC_ID,
        observes: ["self.fishingState", "self.fishingBobber", "self.fishing.nftPond", "pond-ledger chat status", "lootWindow.source=fishing", "inventory.fishing", "stash.walletNfts", "activeBuffs", "fishingResult", "fishingNftCatchResult", "fishingNftHistoryResult", "mintClubRedemptionResult", "fishingSupplyPurchaseResult", "fishingVendorSellResult", "season0Points", "season0DailyPoints"],
        controls: ["startFishing", "reelFishing", "lootCorpse", "cancelFishing", "submitFishingNftClaimTx", "abandonFishingNftCatch", "submitMintClubRedemptionTx", "refreshFishingNftHistory", "purchaseFishingSupply", "purchaseOnchainFishingRod", "sellFishingItems"],
        paidControlRequiresPaymentProof: true,
        note: `Fish through normal room messages. Cast near ${FISHING_ZONE.name}, wait for the bite state, then reel. Catches open a fishing lootWindow; collect it with lootCorpse using that lootWindow npcId/source id. Interact with ${FISHING_POND_STATUS_NPC_ID} for today's onchain-goodie offered/left/reset status. Motherfisher sells bucket of old chum after fishin-lesson with an MFERGPT burn proof. Fish sales happen at fish monger after lost-fishing-shoes; onchain goodies can require an ${ONCHAIN_FISHING_ROD_DEFAULT_LABEL} wallet holding, and Mint Club redemptions are wallet actions at ${MINT_CLUB_REDEMPTION_NPC_ID}.`,
      },
      hotbar: {
        observes: ["combatActions", "inventory.consumables", "inventory.fishingPole", "selected target"],
        controls: ["setHotbarSlot", "interact", "combatAction", "useItem", "startFishing", "reelFishing"],
        note: "Human hotbar slot arrangement is local client preference; agents call the same resulting room actions directly.",
      },
      errands: {
        observes: ["quests", "questOffers", "questTurnIns", "questStatus"],
        controls: ["setQuestFocus", "toggleCompletedQuestVisibility", "acceptQuest", "completeQuest", "cancelQuest", "shareQuestLink"],
      },
      loot: {
        observes: ["lootWindow", "nearbyNpcs.hasLoot"],
        controls: ["lootCorpse"],
        note: "Pass itemId to loot one item, or omit itemId to grab all available loot from the corpse.",
      },
      social: {
        observes: ["chat", "nearbyPlayers", "nearbyPlayers.agentStatus"],
        controls: ["chat", "emote", "agentStatus"],
      },
      targets: {
        observes: ["nearbyPlayers", "nearbyNpcs"],
        controls: ["selectTarget", "selectSelfTarget", "combatAction.target", "interact", "moveNearPlayer", "moveNearNpc"],
      },
      traits: {
        npcId: "traits-mfer",
        observes: ["appearanceTraits", "traitUpdateResult"],
        controls: ["selectTraitCategory", "setTrait", "clearTrait", "randomizeTraits", "updateTraits"],
        paidControlRequiresPaymentProof: true,
      },
      respec: {
        npcId: RESPEC_MFER_NPC_ID,
        observes: ["talentPoints", "talents", "talentRespecResult"],
        controls: ["respecTalents"],
        paidControlRequiresPaymentProof: true,
        note: "Burn MFERGPT once, then submit respecTalents with the payment proof. The server refunds spent talent ranks to talentPoints and clears ranked talents.",
      },
      potionShop: {
        npcId: POTION_SHOP_NPC_ID,
        observes: ["potionShop", "potionShopPurchaseResult"],
        controls: ["selectPotionShopItem", "selectPotionShopQuantity", "purchasePotionShopItem"],
        paidControlRequiresPaymentProof: true,
      },
      trashVendor: {
        npcId: TRASH_VENDOR_NPC_ID,
        observes: ["inventory", "trashVendor", "trashVendorSellResult", "season0Points", "season0DailyPoints"],
        controls: ["sellTrashItems"],
        paidControlRequiresPaymentProof: false,
        note: "Sell only catalog trash items through the normal sellTrashItems room message. The server applies Season 0 caps and declared-agent reward rules.",
      },
      cryptoStore: {
        npcId: "crypto-mfer",
        observes: ["walletBalances", "contractPrices", "marketQuotes", "chainGearOwnership", "inventory"],
        controls: [
          "connectWallet",
          "refreshWalletBalances",
          "selectGearType",
          "buyGearWithEth",
          "buyGearWithMfer",
          "buyGearWithMferGpt",
          "mintSeasonPassWithEth",
          "mintSeasonPassWithMfer",
          "mintSeasonPassWithMferGpt",
          "configureLocalCryptoContracts",
          "registerChainGear",
        ],
        note: "Gear/pass purchases are wallet transactions. After gear mints, call registerChainGear through the room to add owned gear to inventory.",
      },
      swap: {
        npcId: "swap-mfer",
        observes: ["walletBalances"],
        controls: ["setSwapAmount", "setSwapSlippage", "quoteMferGptSwap", "swapEthForMferGpt", "copyMferGptContract", "openUniswapFallback"],
        note: "Swap is a wallet/onchain action. Humans use swap-mfer or the swap menu; configured headless agents use swap_eth_for_mfergpt. Both use the Base ETH to MFERGPT Uniswap v4 route.",
      },
      map: {
        observes: ["world.hubs", "world.roads", "world.landmarks", "players", "npcs"],
        controls: ["setQuestFocus", "inspectMapPoint", "move", "travelRoute"],
      },
      settings: {
        observes: ["graphicsQuality", "audio", "nameplates"],
        controls: ["setGraphicsQuality", "setAudio", "setNameplates", "toggleDebugLocalOnly"],
        note: "Settings do not grant gameplay powers or require room messages.",
      },
      system: {
        observes: ["connectionStatus", "deathState"],
        controls: ["respawn", "leave"],
      },
    },
    traits: {
      categories: MFER_APPEARANCE_TRAIT_CATEGORIES,
      declaredAgentModel: "mfergpt",
      forcedForDeclaredAgents: AGENT_MFER_APPEARANCE_FORCED_TRAITS,
      blockedForDeclaredAgents: AGENT_MFER_APPEARANCE_BLOCKED_TRAITS,
      selectionGuidance: AGENT_MFER_APPEARANCE_SELECTION_GUIDANCE,
      note: `Declared agents render with the mferGPT agent model. The trait form still needs valid mfer trait ids for identity metadata; choose style from the agent's identity or play archetype. Declared agents keep the robot face, so saved agent traits force regular eyes and flat mouth, and clipping-prone accessories such as caps, long hair, shades, and glasses should remain unset. ${AGENT_MFER_APPEARANCE_SELECTION_GUIDANCE}`,
    },
    payments: {
      mferGpt: {
        chainId: TRAIT_CHANGE_BASE_CHAIN_ID,
        rpcUrl: TRAIT_CHANGE_BASE_RPC_URL,
        tokenAddress: TRAIT_CHANGE_MFERGPT_TOKEN_ADDRESS,
        burnAddress: TRAIT_CHANGE_BURN_ADDRESS,
        wethAddress: MFERGPT_BASE_WETH_ADDRESS,
        uniswapUniversalRouterAddress: MFERGPT_BASE_UNISWAP_UNIVERSAL_ROUTER_ADDRESS,
        uniswapV4Pool: MFERGPT_BASE_UNISWAP_V4_POOL,
        swap: {
          input: "ETH",
          output: "MFERGPT",
          chainId: TRAIT_CHANGE_BASE_CHAIN_ID,
          route: "Base ETH -> WETH -> MFERGPT via Uniswap v4 Universal Router",
          npcId: "swap-mfer",
          defaultEthAmount: DEFAULT_MFERGPT_SWAP_ETH_AMOUNT,
          defaultSlippageBps: DEFAULT_MFERGPT_SWAP_SLIPPAGE_BPS,
          humanHelp: "Open swap-mfer or the swap menu to swap Base ETH to MFERGPT.",
          agentAction: "swap_eth_for_mfergpt is available when wallet tools are configured and the run's ETH spend cap allows it.",
        },
        season0AgentRequiredBalanceWei: DEFAULT_AGENT_SEASON0_MFERGPT_MIN_BALANCE_WEI,
        season0AgentRequiredBalanceLabel: AGENT_SEASON0_MFERGPT_MIN_BALANCE_LABEL,
        season0AgentRequirementNote: `Declared agents need ${AGENT_SEASON0_MFERGPT_MIN_BALANCE_LABEL} on Base before Season 0 points accrue. Progress still saves below the gate.`,
        season0AgentHumanHelp: `To activate agent Season 0 earning, fund the agent wallet with ${AGENT_SEASON0_MFERGPT_MIN_BALANCE_LABEL}. Humans can use swap-mfer or the swap menu to swap Base ETH to MFERGPT.`,
        season0AgentPointMultiplier: readAgentSeason0PointMultiplier(),
        talentRespec: {
          npcId: RESPEC_MFER_NPC_ID,
          productId: TALENT_RESPEC_PRODUCT_ID,
          amountWei: TALENT_RESPEC_MFERGPT_AMOUNT_WEI,
          amountLabel: TALENT_RESPEC_MFERGPT_AMOUNT_LABEL,
          message: "respecTalents",
        },
      },
    },
    combatActions: COMBAT.actions,
    emotes: EMOTES,
    progression: PROGRESSION,
    equipmentSlots: EQUIPMENT_SLOTS,
    items: Object.fromEntries(Object.entries(ITEMS).map(([id, item]) => {
      const optional = item as {
        value?: number;
        equipment?: unknown;
        consumable?: unknown;
        revealsAllNpcsOnMinimap?: boolean;
      };
      return [id, {
        id,
        name: item.name,
        description: item.description,
        quality: item.quality,
        iconColor: item.iconColor,
        stackable: item.stackable,
        value: optional.value ?? 0,
        equipment: optional.equipment ?? null,
        consumable: optional.consumable ?? null,
        revealsAllNpcsOnMinimap: Boolean(optional.revealsAllNpcsOnMinimap),
      }];
    })),
    talentTrees: TALENT_TREES,
    talents: Object.fromEntries(Object.entries(TALENTS).map(([id, talent]) => {
      const optional = talent as {
        minLevel?: number;
        requires?: unknown;
        unlockAction?: string;
      };
      return [id, {
        id,
        tree: talent.tree,
        nodeId: talent.nodeId,
        name: talent.name,
        description: talent.description,
        maxRank: talent.maxRank,
        minLevel: optional.minLevel ?? 1,
        requires: optional.requires ?? [],
        effectText: talent.effectText,
        effectPerRank: talent.effectPerRank,
        unlockAction: optional.unlockAction ?? "",
      }];
    })),
    potionShop: {
      npcId: POTION_SHOP_NPC_ID,
      productId: POTION_SHOP_PRODUCT_ID,
      items: POTION_SHOP_ITEM_IDS.map((itemId) => ({
        itemId,
        prices: Object.fromEntries(POTION_SHOP_PURCHASE_QUANTITIES.map((quantity) => [
          quantity,
          getPotionShopPrice(quantity as PotionShopPurchaseQuantity, itemId as PotionShopItemId),
        ])),
      })),
      quantities: POTION_SHOP_PURCHASE_QUANTITIES,
    },
    trashVendor: {
      npcId: TRASH_VENDOR_NPC_ID,
      baseSeasonPointValue: getTrashVendorSellValue(1),
      agentItemsPerPoint: AGENT_TRASH_VENDOR_ITEMS_PER_POINT,
      agentPayoutNote: `Declared agents sell complete ${AGENT_TRASH_VENDOR_ITEMS_PER_POINT}-trash bundles for 1 Season 0 point. Remainders stay in inventory.`,
      itemIds: TRASH_VENDOR_ITEM_IDS,
      items: TRASH_VENDOR_ITEM_IDS.map((itemId) => ({
        itemId,
        name: ITEMS[itemId].name,
        description: ITEMS[itemId].description,
        quality: ITEMS[itemId].quality,
        basePoints: getTrashVendorSellValue(1),
      })),
      controls: {
        sellOne: { message: "sellTrashItems", shape: { itemId: "trash item id", quantity: 1 } },
        sellStack: { message: "sellTrashItems", shape: { itemId: "trash item id", quantity: "integer 1..999" } },
        sellAll: { message: "sellTrashItems", shape: { sellAll: true } },
      },
    },
    fishing: {
      zone: {
        id: FISHING_ZONE_ID,
        name: FISHING_ZONE.name,
        x: FISHING_ZONE.x,
        z: FISHING_ZONE.z,
        waterRadius: FISHING_ZONE.waterRadius,
        shoreRadius: FISHING_ZONE.shoreRadius,
      },
      tutorNpcId: FISHING_TUTOR_NPC_ID,
      vendorNpcId: FISHING_VENDOR_NPC_ID,
      statusNpcId: FISHING_POND_STATUS_NPC_ID,
      redemptionNpcId: MINT_CLUB_REDEMPTION_NPC_ID,
      controls: {
        cast: { message: "startFishing", shape: { zoneId: FISHING_ZONE_ID } },
        reel: { message: "reelFishing", shape: { attemptId: "current fishingAttemptId, optional" } },
        lootCatch: { message: "lootCorpse", shape: { npcId: "lootWindow.npcId from a fishing lootWindow" } },
        cancel: { message: "cancelFishing", shape: {} },
        buyChum: { message: "purchaseFishingSupply", shape: { payment: "MFERGPT burn proof for bucket of old chum" } },
        mintOnchainFishingRod: { message: "purchaseOnchainFishingRod", shape: {}, note: "local/test server-mint fallback only; production rod mints are wallet transactions against the configured NFT mint contract" },
        sellOne: { message: "sellFishingItems", shape: { itemId: "sellable fish item id", quantity: 1 } },
        sellStack: { message: "sellFishingItems", shape: { itemId: "sellable fish item id", quantity: "integer 1..999" } },
        sellAll: { message: "sellFishingItems", shape: { sellAll: true } },
        checkDailyNftStatus: { message: "interact", shape: { npcId: FISHING_POND_STATUS_NPC_ID } },
        refreshNftHistory: { message: "refreshFishingNftHistory", shape: {} },
        submitNftClaimTx: { message: "submitFishingNftClaimTx", shape: { catchId: "fishingNftCatchResult.catch.catchId", txHash: "player-signed FishingPond.claim tx hash" } },
        forfeitNftClaimOffer: { message: "abandonFishingNftCatch", shape: { catchId: "unsubmitted pond catch id" } },
        submitMintClubRedemptionTx: { message: "submitMintClubRedemptionTx", shape: { catchId: "confirmed pond catch id", txHash: "player-signed Mint Club Bond.burn tx hash", status: "confirmed after wallet receipt" } },
      },
      catchLootNote: "A successful reel sends a normal lootWindow with source=fishing and an npcId/source id such as fishing:<hash>. Inventory and fishin-lesson progress update only after lootCorpse collects that window.",
      lostShoesQuestNote: "After fishin-lesson, fish monger's lost-fishing-shoes quest gives each valid reel a 10% chance to produce old mfer shoe as the quest catch. Regular fish sales remain locked until this quest is completed; /agent-fishing sell_fish returns prerequisite_required with an exact nextRequest for /agent-fishing start plus questId=lost-fishing-shoes, whose scoped runner may complete catalog-declared fishing prerequisites first. Never use /agent-command, generic play_for, unrelated quests, or sellTrashItems as a fallback for fish or NFTs.",
      saleSemantics: {
        regularFish: "sellFishingItems and /agent-fishing operation=sell_fish sell regular offchain fish for Season points after lost-fishing-shoes.",
        nftCatches: "NFT catches use claim_fishing_nft plus a wallet transaction and optional Mint Club redemption. They are never sold by sellFishingItems or sellTrashItems.",
        trash: "sellTrashItems is only for trash explicitly requested by the player.",
      },
      playbook: [
        "If self.fishing.hasPole is false, accept fishin-lesson from Motherfisher first; the loaner pole is enough to start fishing.",
        "Move to the south-center pond shore until self.fishing.nearZone is true, then send startFishing.",
        "Wait while self.fishing.state is casting or waiting; when it becomes bite, send reelFishing before biteWindowMs expires.",
        "If reelFishing returns caught or junk, collect the fishing lootWindow with lootCorpse before expecting inventory or quest progress.",
        "If reelFishing returns nft, that offer immediately uses one of today's NFT catches. Wallet players can use the in-game pond/onchain UI; hosted /agent-fishing and /agent-command stop with walletActionRequired.action=claim_fishing_nft. Headless wallet tooling must sign FishingPond.claim and then send submitFishingNftClaimTx, /agent-fishing operation=submit_claim_tx, or /agent-action action=submit_fishing_nft_claim_tx with the tx hash. It may send abandonFishingNftCatch before tx submission to forfeit the claim while keeping the daily offer spent.",
        "If onchain rod ownership is required, production wallet tooling should mint through the configured rod NFT mint contract or mint URL; the NFT contract is responsible for any 25M MFERGPT burn/payment. purchaseOnchainFishingRod is only the local/test server-mint fallback.",
        "Interact with pond ledger mfer for today's onchain-goodie offer count, remaining NFT catch slots, global cap state, and reset time.",
        "Send refreshFishingNftHistory after wallet actions or on reconnect to refresh pond NFT catches, rod stash rows, daily remaining count, and redemption state.",
        "If a confirmed pond NFT has mintClubRedemption, wallet players can use the in-game onchain-goodies UI to approve the Mint Club Bond if needed, sell/burn 1 ERC-1155 unit, then send submitMintClubRedemptionTx. Headless agents need wallet tooling for the same transaction.",
        "After lost-fishing-shoes is completed, sell eligible fish at fish monger with sellFishingItems.",
      ],
      timing: {
        castMs: FISHING_CAST_MS,
        biteMinMs: FISHING_BITE_MIN_MS,
        biteMaxMs: FISHING_BITE_MAX_MS,
        biteWindowMs: FISHING_BITE_WINDOW_MS,
      },
      chum: {
        itemId: FISHING_CHUM_ITEM_ID,
        price: getFishingSupplyPrice(),
        unlockQuestId: "fishin-lesson",
        effect: "1h +25% rare fish chance",
      },
      nftPond: {
        enabledWhenConfigured: true,
        randomness: FISHING_NFT_POND_RANDOMNESS_NOTE,
        v1Decisions: FISHING_NFT_POND_V1_DECISIONS,
        defaultCatchChanceBps: FISHING_NFT_POND_DEFAULT_CATCH_CHANCE_BPS,
        defaultPerWalletDailyCap: FISHING_NFT_POND_DEFAULT_WALLET_DAILY_CAP,
        defaultGlobalDailyCap: FISHING_NFT_POND_DEFAULT_GLOBAL_DAILY_CAP,
        erc1155CatchAmount: FISHING_NFT_POND_ERC1155_CATCH_AMOUNT,
        rodRequirement: {
          optionalEnvGate: true,
          env: {
            enabled: "MFERLAND_ONCHAIN_FISHING_ROD_ENABLED",
            required: "MFERLAND_ONCHAIN_FISHING_ROD_REQUIRED",
            standard: "MFERLAND_ONCHAIN_FISHING_ROD_STANDARD=ERC721|ERC1155",
            contractAddress: "MFERLAND_ONCHAIN_FISHING_ROD_CONTRACT_ADDRESS",
            tokenId: "MFERLAND_ONCHAIN_FISHING_ROD_TOKEN_ID for ERC-1155",
            chainId: "MFERLAND_ONCHAIN_FISHING_ROD_CHAIN_ID",
            rpcUrl: "MFERLAND_ONCHAIN_FISHING_ROD_RPC_URL",
            mintUrl: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_URL",
            mintPriceAmountWei: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_PRICE_AMOUNT_WEI",
            mintPriceLabel: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_PRICE_LABEL",
            mintMode: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_MODE=wallet|server|url",
            mintContractAddress: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_CONTRACT_ADDRESS, defaults to rod contract",
            mintFunction: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_FUNCTION=mint|mint(address)|mint(uint256)|mint(address,uint256)|manifoldClaim",
            mintInstanceId: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_INSTANCE_ID for Manifold claim pages",
            mintNativeValueWei: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_NATIVE_VALUE_WEI for native mint fees",
            mintPaymentTokenAddress: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_PAYMENT_TOKEN_ADDRESS for optional approval before wallet mint",
            mintPaymentSpenderAddress: "MFERLAND_ONCHAIN_FISHING_ROD_MINT_PAYMENT_SPENDER_ADDRESS, defaults to mint contract",
            adminMintEnabled: "MFERLAND_ONCHAIN_FISHING_ROD_ADMIN_MINT_ENABLED",
          },
          rule: "when enabled and required, the server must confirm the wallet owns the configured rod before issuing an NFT catch voucher; regular fish and junk still work without it",
          mintPrice: {
            amountWei: ONCHAIN_FISHING_ROD_MFERGPT_AMOUNT_WEI,
            label: ONCHAIN_FISHING_ROD_MFERGPT_AMOUNT_LABEL,
          },
          missingRodNotice: "fishingNftCapNotice.kind=rod_required appears once per fishing reset day on the first valid cast without the rod, and fishingNftCapNotice.kind=rod_required_nft_hit appears whenever a completed reel would have produced an NFT but the wallet lacks the rod",
          stashDisplay: "owning wallets see the configured rod in fishingNftHistoryResult.walletNfts, the stash items grid, and the stash pond/NFT tab",
        },
        claimFlow: [
          "server rolls eligible completed reels and persists a catch before issuing a voucher",
          "the persisted offer immediately counts against wallet/global daily NFT catch limits, even if the player closes, forfeits, or lets it expire",
          "server signs an EIP-712 claim voucher with the configured award signer",
          "player signs and pays gas for FishingPond.claim",
          "client submits tx hash through submitFishingNftClaimTx",
          "server confirms only after a successful receipt with CatchClaimed",
        ],
        walletActionRequired: true,
        agentNote: "Hosted bridge agents cannot sign wallet claims internally. When /agent-fishing or /agent-command returns walletActionRequired.action=claim_fishing_nft, wallet-capable callers such as Bankr should submit the provided transaction from the player wallet, then call /agent-fishing operation=submit_claim_tx or /agent-action action=submit_fishing_nft_claim_tx with catchId and txHash before continuing to fish.",
      },
      mintClubRedemption: {
        npcId: MINT_CLUB_REDEMPTION_NPC_ID,
        chainId: MINT_CLUB_BASE_SEPOLIA_CHAIN_ID,
        bondAddress: MINT_CLUB_BASE_SEPOLIA_BOND_ADDRESS,
        erc1155Address: MINT_CLUB_BASE_SEPOLIA_ERC1155_ADDRESS,
        reserveTokenAddress: MINT_CLUB_BASE_SEPOLIA_WETH_ADDRESS,
        reserveTokenSymbol: "WETH",
        defaultSellRoyaltyBps: MINT_CLUB_DEFAULT_SELL_ROYALTY_BPS,
        allowlistEnv: "MFERLAND_MINT_CLUB_REDEMPTION_ALLOWED_COLLECTIONS",
        flow: [
          "server exposes mintClubRedemption only for configured ERC-1155 pond catches",
          "client/wallet reads owned amount, approval, token bond, and sell estimate",
          "player signs approval if needed",
          "player signs Mint Club Bond.burn sell transaction",
          "client submits tx hash through submitMintClubRedemptionTx",
          "server records history only after the Burn event matches the catch",
        ],
        walletActionRequired: true,
        agentNote: "Wallet players can complete this through the in-game onchain-goodies UI. Headless agents should report the required wallet action and wait for wallet tooling; do not fake redemption.",
      },
      agentCatchPenalty: {
        reason: "fish can smell the metal",
        normalCatchChanceMultiplier: FISHING_AGENT_CATCH_CHANCE_MULTIPLIER,
        rareFishChanceMultiplier: FISHING_AGENT_RARE_CHANCE_MULTIPLIER,
        nftCatchChanceMultiplier: FISHING_AGENT_NFT_CHANCE_MULTIPLIER,
        note: "Declared agents use normal fishing room messages, but completed non-quest reels have a 50% extra miss roll, rare fish weight is halved, and NFT pond chance is halved.",
      },
      agentBundleMultiplier: FISHING_AGENT_BUNDLE_MULTIPLIER,
      agentPayoutNote: `Declared agents need each fish bundle size multiplied by ${FISHING_AGENT_BUNDLE_MULTIPLIER}. Fish sales unlock after lost-fishing-shoes is completed.`,
      itemIds: FISHING_SELLABLE_ITEM_IDS,
      items: FISHING_SELLABLE_ITEM_IDS.map((itemId) => {
        const rule = getFishingSaleRule(itemId);
        return {
          itemId,
          name: ITEMS[itemId].name,
          description: ITEMS[itemId].description,
          quality: ITEMS[itemId].quality,
          bundleSize: rule.bundleSize,
          agentBundleSize: getFishingRequiredBundleSize(itemId, true),
          basePoints: getFishingSellAwardPoints(itemId, rule.bundleSize, false),
          pointsPerBundle: rule.seasonPoints,
        };
      }),
    },
    quests: Object.fromEntries(Object.entries(QUESTS).map(([id, quest]) => {
      const optional = quest as {
        turnInNpcId?: string;
        requiredQuestId?: string;
        requiredItemId?: string;
        objectives?: unknown;
        defeatNpcModels?: unknown;
        defeatNpcRoles?: unknown;
        defeatNpcIdPrefixes?: unknown;
        dropNpcModels?: unknown;
        dropNpcRoles?: unknown;
        dropNpcIdPrefixes?: unknown;
        nextQuestId?: string;
        encounterType?: string;
        groupSuggestion?: string;
        suggestedPlayerCount?: number;
        soloWarning?: string;
        encounterPrepNpcIds?: unknown;
        agentHints?: unknown;
      };
      return [id, {
        id,
        title: quest.title,
        giverNpcId: quest.giverNpcId,
        turnInNpcId: optional.turnInNpcId ?? quest.giverNpcId,
        description: quest.description,
        objectiveLabel: quest.objectiveLabel,
        turnInLabel: quest.turnInLabel,
        required: quest.required,
        requiredQuestId: optional.requiredQuestId ?? "",
        requiredItemId: optional.requiredItemId ?? "",
        defeatNpcModels: optional.defeatNpcModels ?? [],
        defeatNpcRoles: optional.defeatNpcRoles ?? [],
        defeatNpcIdPrefixes: optional.defeatNpcIdPrefixes ?? [],
        dropNpcModels: optional.dropNpcModels ?? [],
        dropNpcRoles: optional.dropNpcRoles ?? [],
        dropNpcIdPrefixes: optional.dropNpcIdPrefixes ?? [],
        objectives: optional.objectives ?? [],
        xpReward: quest.xpReward,
        nextQuestId: optional.nextQuestId ?? "",
        encounterType: optional.encounterType ?? "solo",
        groupSuggestion: optional.groupSuggestion ?? "",
        suggestedPlayerCount: optional.suggestedPlayerCount ?? 1,
        soloWarning: optional.soloWarning ?? "",
        encounterPrepNpcIds: optional.encounterPrepNpcIds ?? [],
        agentHints: optional.agentHints ?? {},
      }];
    })),
    world: {
      hubs: WORLD_HUBS,
      roads: WORLD_ROADS,
      landmarks: WORLD_LANDMARKS,
    },
  };
}
