import { existsSync } from "node:fs";
import { chmod, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

console.error([
  "mferland-agent wallet:create is an optional disposable-wallet helper.",
  "For production, use an agent-controlled wallet/signer you already own or manage.",
  "That can be a private key, Bankr/MPC signer, custody API, local wallet, or another signing backend.",
  "The only protocol requirement is that the agent can sign the /wallet-auth-challenge message for its wallet address.",
  "Do not fund a generated disposable wallet with meaningful value unless you securely store and manage the key.",
].join("\n"));

const privateKey = generatePrivateKey();
const account = privateKeyToAccount(privateKey);
const outputPath = nextAvailableGeneratedEnvPath();

if (process.argv.includes("--json")) {
  console.log(JSON.stringify({
    address: account.address,
    privateKey,
  }, null, 2));
} else {
  await writeFile(outputPath, [
    "# Generated by npm run wallet:create for a disposable mferland agent wallet.",
    "# This file is ignored by the mferland repo .gitignore. Keep it secret.",
    `# address=${account.address}`,
    `AGENT_PRIVATE_KEY=${privateKey}`,
    "",
  ].join("\n"), { mode: 0o600 });
  await chmod(outputPath, 0o600).catch(() => undefined);
  console.log(JSON.stringify({
    address: account.address,
    privateKeyFile: outputPath,
    next: `copy AGENT_PRIVATE_KEY from ${outputPath} into .env, or run with AGENT_ENV_FILE=${outputPath}`,
  }, null, 2));
}

function nextAvailableGeneratedEnvPath() {
  const basePath = resolve(process.cwd(), ".env.generated-wallet");
  if (!existsSync(basePath)) return basePath;
  return resolve(process.cwd(), `.env.generated-wallet.${Date.now()}`);
}
