export const COMBAT = {
  manaRegenDelayMs: 5000,
  healthRegenDelayMs: 10000,
  defeatedDespawnMs: 6500,
  defeatedRespawnMs: 12000,
  castPushbackMs: 500,
  fireblastProjectileSpeed: 24,
  fireblastMinTravelMs: 320,
  fireblastMaxTravelMs: 1100,
  stationaryInputThreshold: 0.05,
  actions: {
    attack: {
      label: "bonk",
      damage: 4,
      cooldownMs: 1500,
      minRange: 0,
      maxRange: 5,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: false,
    },
    shoot: {
      label: "peg",
      damage: 10,
      cooldownMs: 2000,
      minRange: 4.0,
      maxRange: 40,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: true,
    },
    signalShot: {
      label: "ping",
      damage: 12,
      cooldownMs: 6000,
      minRange: 4.0,
      maxRange: 34,
      manaCost: 10,
      castTimeMs: 0,
      requiresStationary: false,
    },
    fireblast: {
      label: "burn post",
      damage: 20,
      cooldownMs: 0,
      minRange: 0,
      maxRange: 30,
      manaCost: 14,
      castTimeMs: 3500,
      requiresStationary: true,
    },
    frostNova: {
      label: "cold take",
      damage: 5,
      cooldownMs: 12000,
      minRange: 0,
      maxRange: 6.5,
      manaCost: 12,
      castTimeMs: 0,
      requiresStationary: false,
      freezeMs: 3000,
    },
    heal: {
      label: "patch up",
      damage: 0,
      healing: 34,
      cooldownMs: 5000,
      minRange: 0,
      maxRange: 24,
      manaCost: 16,
      castTimeMs: 2000,
      requiresStationary: true,
      threatMultiplier: 0.55,
      threatRadius: 20,
    },
    taunt: {
      label: "talk shit",
      damage: 0,
      cooldownMs: 10000,
      minRange: 0,
      maxRange: 12,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: false,
      forceMs: 3000,
      threat: 140,
    },
    whirlwind: {
      label: "spin out",
      damage: 9,
      cooldownMs: 9000,
      minRange: 0,
      maxRange: 4.5,
      manaCost: 10,
      castTimeMs: 0,
      requiresStationary: false,
      threatBonus: 22,
    },
    multishot: {
      label: "thread spray",
      damage: 9,
      cooldownMs: 10000,
      minRange: 4,
      maxRange: 36,
      manaCost: 12,
      castTimeMs: 0,
      requiresStationary: true,
      maxTargets: 3,
      splashRadius: 8,
    },
    iceBlast: {
      label: "freeze post",
      damage: 14,
      cooldownMs: 0,
      minRange: 0,
      maxRange: 28,
      manaCost: 12,
      castTimeMs: 3500,
      requiresStationary: true,
      slowMs: 4500,
      slowMultiplier: 0.62,
    },
  },
} as const;
