export const COMBAT = {
  manaRegenDelayMs: 5000,
  healthRegenDelayMs: 10000,
  defeatedDespawnMs: 6500,
  defeatedRespawnMs: 12000,
  castPushbackMs: 500,
  fireblastProjectileSpeed: 24,
  fireblastMinTravelMs: 320,
  fireblastMaxTravelMs: 1100,
  stationaryInputThreshold: 0.05,
  actions: {
    attack: {
      label: "Attack",
      damage: 6,
      cooldownMs: 1500,
      minRange: 0,
      maxRange: 5,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: false,
    },
    shoot: {
      label: "Shoot",
      damage: 8,
      cooldownMs: 2000,
      minRange: 4.0,
      maxRange: 40,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: true,
    },
    fireblast: {
      label: "Fireblast",
      damage: 16,
      cooldownMs: 0,
      minRange: 0,
      maxRange: 30,
      manaCost: 10,
      castTimeMs: 4000,
      requiresStationary: true,
    },
    frostNova: {
      label: "Frost Nova",
      damage: 4,
      cooldownMs: 10000,
      minRange: 0,
      maxRange: 6.5,
      manaCost: 8,
      castTimeMs: 0,
      requiresStationary: false,
      freezeMs: 4000,
    },
  },
} as const;
