export const COMBAT = {
  manaRegenDelayMs: 5000,
  healthRegenDelayMs: 10000,
  defeatedDespawnMs: 6500,
  defeatedRespawnMs: 12000,
  castPushbackMs: 500,
  fireblastProjectileSpeed: 24,
  fireblastMinTravelMs: 320,
  fireblastMaxTravelMs: 1100,
  stationaryInputThreshold: 0.05,
  actions: {
    attack: {
      label: "Attack",
      damage: 6,
      cooldownMs: 1500,
      minRange: 0,
      maxRange: 5,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: false,
    },
    shoot: {
      label: "Shoot",
      damage: 8,
      cooldownMs: 2000,
      minRange: 4.0,
      maxRange: 40,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: true,
    },
    signalShot: {
      label: "Signal Shot",
      damage: 12,
      cooldownMs: 6000,
      minRange: 4.0,
      maxRange: 34,
      manaCost: 8,
      castTimeMs: 0,
      requiresStationary: false,
    },
    fireblast: {
      label: "Fireblast",
      damage: 16,
      cooldownMs: 0,
      minRange: 0,
      maxRange: 30,
      manaCost: 12,
      castTimeMs: 4000,
      requiresStationary: true,
    },
    frostNova: {
      label: "Frost Nova",
      damage: 4,
      cooldownMs: 10000,
      minRange: 0,
      maxRange: 6.5,
      manaCost: 10,
      castTimeMs: 0,
      requiresStationary: false,
      freezeMs: 4000,
    },
    heal: {
      label: "Heal",
      damage: 0,
      healing: 24,
      cooldownMs: 5000,
      minRange: 0,
      maxRange: 24,
      manaCost: 10,
      castTimeMs: 1800,
      requiresStationary: true,
      threatMultiplier: 0.45,
      threatRadius: 18,
    },
    taunt: {
      label: "Taunt",
      damage: 0,
      cooldownMs: 11000,
      minRange: 0,
      maxRange: 12,
      manaCost: 0,
      castTimeMs: 0,
      requiresStationary: false,
      forceMs: 3000,
      threat: 90,
    },
    whirlwind: {
      label: "Whirlwind",
      damage: 7,
      cooldownMs: 8000,
      minRange: 0,
      maxRange: 4.5,
      manaCost: 6,
      castTimeMs: 0,
      requiresStationary: false,
      threatBonus: 10,
    },
    multishot: {
      label: "Multishot",
      damage: 7,
      cooldownMs: 10000,
      minRange: 4,
      maxRange: 36,
      manaCost: 8,
      castTimeMs: 0,
      requiresStationary: true,
      maxTargets: 3,
      splashRadius: 8,
    },
    iceBlast: {
      label: "Ice Blast",
      damage: 10,
      cooldownMs: 0,
      minRange: 0,
      maxRange: 28,
      manaCost: 11,
      castTimeMs: 4000,
      requiresStationary: true,
      slowMs: 3500,
      slowMultiplier: 0.58,
    },
  },
} as const;
