export const QUESTS = {
  "mfer-beginnings": {
    title: "gm rounds",
    giverNpcId: "og-mfer",
    turnInNpcId: "dao-mfer",
    description: "OG porch mfer sends you on a plaza lap. Sartoshi's gone, the town's still breathing, and the first lesson is seeing who stayed posted.",
    objectiveLabel: "check in with oldhead mfer in the plaza",
    turnInLabel: "talk to oldhead mfer",
    required: 1,
    xpReward: 23,
    autoReady: true,
    nextQuestId: "set-your-traits",
  },
  "set-your-traits": {
    title: "claim your look",
    giverNpcId: "traits-mfer",
    description: "Traits mfer has the mirror rig open. Stop looking like a default tab and claim a look the town can recognize.",
    objectiveLabel: "save your look at traits mfer",
    turnInLabel: "show traits mfer your claimed look",
    required: 1,
    requiredQuestId: "mfer-beginnings",
    xpReward: 19,
    nextQuestId: "dao-tour",
  },
  "dao-tour": {
    title: "plant seeds, not promises",
    giverNpcId: "dao-mfer",
    turnInNpcId: "fountain-mfer",
    description: "Oldhead mfer says there is no roadmap, no official plan, and no one coming to organize this for you. There are oldheads, side-eyes, smoke spots, and small things mfers actually build.",
    objectiveLabel: "find fountain rail mfer at the plaza fountain",
    turnInLabel: "talk to fountain rail mfer",
    required: 1,
    requiredQuestId: "set-your-traits",
    xpReward: 26,
    autoReady: true,
    nextQuestId: "fountain-vibes",
  },
  "fountain-vibes": {
    title: "still here",
    giverNpcId: "fountain-mfer",
    turnInNpcId: "og-mfer",
    description: "Fountain rail mfer says the town survived because mfers kept showing up after Sartoshi disappeared. Bring that back to OG porch mfer.",
    objectiveLabel: "head back to OG porch mfer",
    turnInLabel: "return to OG porch mfer",
    required: 1,
    requiredQuestId: "dao-tour",
    xpReward: 26,
    autoReady: true,
    nextQuestId: "sealed-note",
  },
  "sealed-note": {
    title: "pass the seed note",
    giverNpcId: "og-mfer",
    turnInNpcId: "wearables-mfer",
    description: "OG porch mfer hands you a folded seed note for drip desk mfer. It's about what gets built next, and it is still none of your business.",
    objectiveLabel: "deliver the folded seed note to drip desk mfer",
    turnInLabel: "hand the folded seed note to drip desk mfer",
    required: 1,
    requiredQuestId: "fountain-vibes",
    startItemId: "sealed-note",
    requiredItemId: "sealed-note",
    consumeItem: true,
    xpReward: 34,
    nextQuestId: "farm-road-handoff",
  },
  "farm-road-handoff": {
    title: "airdrop farm handoff",
    giverNpcId: "wearables-mfer",
    turnInNpcId: "hogwatch-mfer",
    description: "Drip desk mfer points you toward the busted farm, where people are still waiting for the next drop and claim-brain is starting to leak back into town.",
    objectiveLabel: "find claimwatch mfer by the busted farm",
    turnInLabel: "talk to claimwatch mfer",
    required: 1,
    requiredQuestId: "sealed-note",
    xpReward: 30,
    autoReady: true,
    nextQuestId: "boar-bristle-cull",
  },
  "ask-mfergpt": {
    title: "grab some lore",
    giverNpcId: "wearables-mfer",
    turnInNpcId: "mfergpt",
    description: "Drip desk mfer says town history is scattered but alive. Ask mferGPT for one lore fragment and see what shakes loose.",
    objectiveLabel: "ask @mferGPT for a lore fragment",
    turnInLabel: "check in with mferGPT",
    required: 1,
    requiredQuestId: "sealed-note",
    xpReward: 64,
  },
  "mfergpt-checkin": {
    title: "signal check",
    giverNpcId: "mfergpt",
    description: "mferGPT wants one clean gm to the agent. Say @mfergpt in chat and make sure the signal still answers.",
    objectiveLabel: "say @mfergpt in chat",
    turnInLabel: "return to mferGPT",
    required: 1,
    requiredQuestId: "mfer-beginnings",
    chatMention: "@mfergpt",
    xpReward: 15,
  },
  "tweet-town-link": {
    title: "post the plaza",
    giverNpcId: "mfergpt",
    description: "mferGPT wants the plaza signal pushed out. Open the tweet composer, post it when you mean it, then claim the ping.",
    objectiveLabel: "post the mferland signal",
    turnInLabel: "return to mferGPT",
    required: 1,
    requiredQuestId: "mfer-beginnings",
    socialAction: "tweet",
    xpReward: 15,
  },
  "boar-bristle-cull": {
    title: "hogs in the claim pile",
    giverNpcId: "hogwatch-mfer",
    description: "Claimwatch mfer says the hogs rooted through old airdrop crates and scattered the stash. Clear them before the farmers get even worse.",
    objectiveLabel: "clear 10 hogs from the claim pile",
    turnInLabel: "return to claimwatch mfer",
    required: 10,
    requiredQuestId: "farm-road-handoff",
    defeatNpcModels: ["hog"],
    xpReward: 94,
    nextQuestId: "feral-farmers",
  },
  "feral-farmers": {
    title: "next drop sickness",
    giverNpcId: "hogwatch-mfer",
    description: "Claimwatch mfer says the airdrop addicts posted themselves into a trance: missed Creyzies, EOS cope, Nakamigos conspiracies, the whole sad loop.",
    objectiveLabel: "drop bran, mae, and sol at airdrop farm",
    turnInLabel: "return to claimwatch mfer",
    required: 3,
    requiredQuestId: "boar-bristle-cull",
    xpReward: 105,
    objectives: [
      { id: "farmhand-bran", label: "drop creyzie chaser bran" },
      { id: "farmhand-mae", label: "drop just-missed-it mae" },
      { id: "field-mage-sol", label: "drop nakamigo truther sol" },
    ],
    nextQuestId: "hog-livers",
  },
  "hog-livers": {
    title: "eos recovery",
    giverNpcId: "hogwatch-mfer",
    description: "The hogs swallowed old EOS pieces, pass fragments, and whatever claim stash the farm had left. Recover enough to stabilize the route.",
    objectiveLabel: "recover 5 chewed EOS from farm-road hogs",
    turnInLabel: "return to claimwatch mfer",
    required: 5,
    requiredQuestId: "feral-farmers",
    requiredItemId: "hog-liver",
    consumeItem: true,
    dropRate: 0.66,
    xpReward: 135,
    nextQuestId: "field-camp-delivery",
  },
  "field-camp-delivery": {
    title: "town route still works",
    giverNpcId: "hogwatch-mfer",
    turnInNpcId: "field-guide-mfer",
    description: "Take the update southwest down the dirt road. The farm is cooked, but the route still connects back to town, and that means the world still works.",
    objectiveLabel: "carry claimwatch's update southwest to route post mfer",
    turnInLabel: "reach route post mfer",
    required: 1,
    requiredQuestId: "hog-livers",
    autoReady: true,
    xpReward: 83,
    rewardItemIds: ["field-patched-hoodie"],
    nextQuestId: "route-patrol-daily",
  },
  "route-patrol-daily": {
    title: "clear the claim route",
    giverNpcId: "field-guide-mfer",
    description: "Every day the farm gets stupid again. Clear hogs and airdrop-burnt mfers so people can still move through.",
    objectiveLabel: "clear 6 hogs or claim-burnt mfers near route post",
    turnInLabel: "report back to route post mfer",
    required: 6,
    requiredQuestId: "field-camp-delivery",
    defeatNpcModels: ["hog"],
    defeatNpcRoles: ["farmer"],
    repeatCooldownMs: 86_400_000,
    repeatLabel: "daily",
    xpReward: 158,
    nextQuestId: "hog-loop",
  },
  "hog-loop": {
    title: "eos hog loop",
    giverNpcId: "pen-keeper-mfer",
    description: "Claim booth mfer pays for the daily cleanup because the hogs keep eating the stash again and everyone keeps acting surprised.",
    objectiveLabel: "clear 5 stash-eating hogs near claim booth",
    turnInLabel: "return to claim booth mfer",
    required: 5,
    requiredQuestId: "route-patrol-daily",
    defeatNpcModels: ["hog"],
    repeatCooldownMs: 86_400_000,
    repeatLabel: "daily",
    xpReward: 101,
    nextQuestId: "ridge-dispatch",
  },
  "ridge-dispatch": {
    title: "follow the bad signal",
    giverNpcId: "field-guide-mfer",
    turnInNpcId: "ridge-guide-mfer",
    description: "Carry the route ping toward the uplink zone where the signal has gone wrong. Hit the 0.069-mile cut, take the 4:20 turn, and do not follow the noise.",
    objectiveLabel: "carry the route ping east to signal post mfer",
    turnInLabel: "reach signal post mfer",
    required: 1,
    requiredQuestId: "hog-loop",
    autoReady: true,
    xpReward: 135,
    nextQuestId: "signal-scraps",
  },
  "signal-scraps": {
    title: "fried uplink scraps",
    giverNpcId: "ridge-guide-mfer",
    description: "Signal post mfer wants the leftover shards falling off the crew jamming the upper trail. If it still buzzes, bring it back.",
    objectiveLabel: "collect 4 fried uplink shards on Signal Ridge",
    turnInLabel: "return the shards to signal post mfer",
    required: 4,
    requiredQuestId: "ridge-dispatch",
    requiredItemId: "signal-scrap",
    consumeItem: true,
    dropRate: 0.62,
    xpReward: 195,
    rewardItemIds: ["ridge-runner-beanie"],
    nextQuestId: "cut-the-static",
  },
  "cut-the-static": {
    title: "kill the repeaters",
    giverNpcId: "beacon-keeper-mfer",
    description: "Uplink shack mfer wants the whole bad ridge stack cut loose: the operator, the repeater, and the helper shell still answering the wrong question.",
    objectiveLabel: "drop operator vex, repeater pax, and echo-shell ori",
    turnInLabel: "report to uplink shack mfer",
    required: 3,
    requiredQuestId: "signal-scraps",
    xpReward: 240,
    objectives: [
      { id: "ridge-raider-vex", label: "drop operator vex" },
      { id: "ridge-raider-pax", label: "drop repeater pax" },
      { id: "static-mage-ori", label: "drop echo-shell ori" },
    ],
    nextQuestId: "baron-of-static",
  },
  "baron-of-static": {
    title: "log off the centralizer",
    giverNpcId: "beacon-keeper-mfer",
    description: "The Centralizer is what happens when bad signal, control, and repetition become one big body. Bring friends and log it off.",
    objectiveLabel: "drop The Centralizer at uplink shack",
    turnInLabel: "return to uplink shack mfer",
    required: 1,
    requiredQuestId: "cut-the-static",
    xpReward: 353,
    objectives: [
      { id: "static-baron-nox", label: "drop The Centralizer" },
    ],
    rewardItemIds: ["baron-breaker-board"],
    nextQuestId: "ogre-raid-daily",
  },
  "ogre-raid-daily": {
    title: "too much signal",
    giverNpcId: "beacon-keeper-mfer",
    description: "Every 24 hours the uplink overloads into one huge, loud, fully unnecessary body. That's the raid.",
    objectiveLabel: "drop too much signal at uplink shack",
    turnInLabel: "report back to uplink shack mfer",
    required: 1,
    requiredQuestId: "baron-of-static",
    xpReward: 525,
    objectives: [
      { id: "raid-ogre-mfer", label: "drop too much signal" },
    ],
    repeatCooldownMs: 86_400_000,
    repeatLabel: "daily raid",
  },
} as const;

export const QUEST_IDS = Object.keys(QUESTS) as Array<keyof typeof QUESTS>;
