export const QUESTS = {
  "mfer-beginnings": {
    title: "one honest lap",
    giverNpcId: "og-mfer",
    turnInNpcId: "dao-mfer",
    description: "OG porch mfer does not care about speeches. Make one lap, find the board, and prove you can move through town without acting official.",
    objectiveLabel: "check in with board mfer",
    turnInLabel: "talk to board mfer",
    required: 1,
    xpReward: 30,
    autoReady: true,
    nextQuestId: "dao-tour",
  },
  "dao-tour": {
    title: "board check",
    giverNpcId: "dao-mfer",
    turnInNpcId: "fountain-mfer",
    description: "The board got its one useful moment out of you. Now go find fountain rail mfer, where people actually stand around and know things.",
    objectiveLabel: "find fountain rail mfer",
    turnInLabel: "talk to fountain rail mfer",
    required: 1,
    requiredQuestId: "mfer-beginnings",
    xpReward: 35,
    autoReady: true,
    nextQuestId: "fountain-vibes",
  },
  "fountain-vibes": {
    title: "real town hall",
    giverNpcId: "fountain-mfer",
    turnInNpcId: "og-mfer",
    description: "Fountain rail mfer wants you to admit the obvious: the fountain runs this place better than any sign or schedule.",
    objectiveLabel: "head back to OG porch mfer",
    turnInLabel: "return to OG porch mfer",
    required: 1,
    requiredQuestId: "dao-tour",
    xpReward: 35,
    autoReady: true,
    nextQuestId: "sealed-note",
  },
  "sealed-note": {
    title: "don't open that",
    giverNpcId: "og-mfer",
    turnInNpcId: "wearables-mfer",
    description: "OG porch mfer hands you a folded note for drip desk mfer. it's offchain, direct, and none of your business.",
    objectiveLabel: "deliver the folded note",
    turnInLabel: "bring the note to drip desk mfer",
    required: 1,
    requiredQuestId: "fountain-vibes",
    startItemId: "sealed-note",
    requiredItemId: "sealed-note",
    consumeItem: true,
    xpReward: 45,
    nextQuestId: "boar-bristle-cull",
  },
  "ask-mfergpt": {
    title: "ask the agent",
    giverNpcId: "wearables-mfer",
    turnInNpcId: "mfergpt",
    description: "Drip desk mfer says the cleanest way out of plaza confusion is to ask mferGPT where to go next.",
    objectiveLabel: "ask @mferGPT where to go",
    turnInLabel: "check in with mferGPT",
    required: 1,
    requiredQuestId: "sealed-note",
    xpReward: 85,
  },
  "mfergpt-checkin": {
    title: "ask mferGPT",
    giverNpcId: "mfergpt",
    description: "mferGPT wants one clean signal check. say @mfergpt in chat and let it answer.",
    objectiveLabel: "say @mfergpt in chat",
    turnInLabel: "return to mferGPT",
    required: 1,
    requiredQuestId: "mfer-beginnings",
    chatMention: "@mfergpt",
    xpReward: 20,
  },
  "tweet-town-link": {
    title: "post the map",
    giverNpcId: "mfergpt",
    description: "mferGPT wants the town link sent out. open the tweet composer, post it when you mean it, then claim the ping.",
    objectiveLabel: "tweet the mferland link",
    turnInLabel: "return to mferGPT",
    required: 1,
    requiredQuestId: "mfer-beginnings",
    socialAction: "tweet",
    xpReward: 20,
  },
  "boar-bristle-cull": {
    title: "boar warmup",
    giverNpcId: "hogwatch-mfer",
    description: "hogwatch mfer wants the wild boars thinned before anyone starts picking fights with red-eye farmers.",
    objectiveLabel: "kill 10 wild boars",
    turnInLabel: "return to hogwatch mfer",
    required: 10,
    requiredQuestId: "sealed-note",
    defeatNpcModels: ["hog"],
    xpReward: 125,
    nextQuestId: "farmhand-bandanas",
  },
  "farmhand-bandanas": {
    title: "reply-loop rags",
    giverNpcId: "wearables-mfer",
    description: "Drip desk mfer can stitch warning flags once the red-eye farmhands stop making the road worse.",
    objectiveLabel: "drop 4 red-eye farmhands",
    turnInLabel: "return to drip desk mfer",
    required: 4,
    requiredQuestId: "boar-bristle-cull",
    defeatNpcRoles: ["farmer"],
    xpReward: 105,
    nextQuestId: "feral-farmers",
  },
  "feral-farmers": {
    title: "engagement farming",
    giverNpcId: "hogwatch-mfer",
    description: "Hogwatch mfer says the farm crew posted themselves into a trance. Knock out the named offenders before the whole road catches it.",
    objectiveLabel: "drop bran, mae, and sol",
    turnInLabel: "return to hogwatch mfer",
    required: 3,
    requiredQuestId: "farmhand-bandanas",
    xpReward: 140,
    objectives: [
      { id: "farmhand-bran", label: "drop red-eye mfer bran" },
      { id: "farmhand-mae", label: "drop red-eye mfer mae" },
      { id: "field-mage-sol", label: "drop signal-sick mfer sol" },
    ],
    nextQuestId: "hog-livers",
  },
  "hog-livers": {
    title: "gross road fix",
    giverNpcId: "hogwatch-mfer",
    description: "Hogwatch mfer needs five hog livers for a fix nobody wants explained. The road stays open however it stays open.",
    objectiveLabel: "collect 5 hog loop livers",
    turnInLabel: "return to hogwatch mfer",
    required: 5,
    requiredQuestId: "feral-farmers",
    requiredItemId: "hog-liver",
    consumeItem: true,
    dropRate: 0.66,
    xpReward: 180,
    nextQuestId: "field-camp-delivery",
  },
  "field-camp-delivery": {
    title: "road still works",
    giverNpcId: "hogwatch-mfer",
    turnInNpcId: "field-guide-mfer",
    description: "Take the update north. The farm is ugly, but the dirt still connects to the post and that's enough for now.",
    objectiveLabel: "carry hogwatch's update to route board mfer",
    turnInLabel: "reach route board mfer",
    required: 1,
    requiredQuestId: "hog-livers",
    autoReady: true,
    xpReward: 110,
    rewardItemIds: ["field-patched-hoodie"],
    nextQuestId: "route-patrol-daily",
  },
  "route-patrol-daily": {
    title: "keep the route clean",
    giverNpcId: "field-guide-mfer",
    description: "Route board mfer keeps one daily rule: if it starts looking too stupid out there, go make it less stupid.",
    objectiveLabel: "clear 6 farm-road enemies",
    turnInLabel: "report back to route board mfer",
    required: 6,
    requiredQuestId: "field-camp-delivery",
    defeatNpcModels: ["hog"],
    defeatNpcRoles: ["farmer"],
    repeatCooldownMs: 86_400_000,
    repeatLabel: "daily",
    xpReward: 210,
    nextQuestId: "hog-loop",
  },
  "hog-loop": {
    title: "hog loop, again",
    giverNpcId: "pen-keeper-mfer",
    description: "Loop booth mfer pays for another sweep because the hog loop resets faster than anyone learns from it.",
    objectiveLabel: "clear 5 wild hogs",
    turnInLabel: "return to loop booth mfer",
    required: 5,
    requiredQuestId: "route-patrol-daily",
    defeatNpcModels: ["hog"],
    repeatCooldownMs: 300_000,
    repeatLabel: "repeatable",
    xpReward: 135,
    nextQuestId: "ridge-dispatch",
  },
  "ridge-dispatch": {
    title: "take it uptrail",
    giverNpcId: "field-guide-mfer",
    turnInNpcId: "ridge-guide-mfer",
    description: "Carry the route ping up the 0.069-mile cut, hang the 4:20 turn, and hand it to ridge post mfer without wandering into the noise.",
    objectiveLabel: "carry the route ping to ridge post mfer",
    turnInLabel: "reach ridge post mfer",
    required: 1,
    requiredQuestId: "hog-loop",
    autoReady: true,
    xpReward: 180,
    nextQuestId: "signal-scraps",
  },
  "signal-scraps": {
    title: "fried relay scraps",
    giverNpcId: "ridge-guide-mfer",
    description: "Ridge post mfer wants the leftover pieces falling off the crew jamming the upper trail. If it still buzzes, bring it back.",
    objectiveLabel: "collect 4 fried relay scraps",
    turnInLabel: "return the scraps to ridge post mfer",
    required: 4,
    requiredQuestId: "ridge-dispatch",
    requiredItemId: "signal-scrap",
    consumeItem: true,
    dropRate: 0.62,
    xpReward: 260,
    rewardItemIds: ["ridge-runner-beanie"],
    nextQuestId: "cut-the-static",
  },
  "cut-the-static": {
    title: "pull the plug",
    giverNpcId: "beacon-keeper-mfer",
    description: "Relay shack mfer wants the whole bad ridge stack cut loose: the runner, the stray, and the broken shell talking to itself.",
    objectiveLabel: "drop vex, pax, and the broken shell",
    turnInLabel: "report to relay shack mfer",
    required: 3,
    requiredQuestId: "signal-scraps",
    xpReward: 320,
    objectives: [
      { id: "ridge-raider-vex", label: "drop runner vex" },
      { id: "ridge-raider-pax", label: "drop off-route pax" },
      { id: "static-mage-ori", label: "drop broken mferGPT shell" },
    ],
    nextQuestId: "baron-of-static",
  },
  "baron-of-static": {
    title: "log off the baron",
    giverNpcId: "beacon-keeper-mfer",
    description: "The Static Baron is what happens when bad signal finds a spine. Bring friends and separate it from its confidence.",
    objectiveLabel: "drop the Static Baron",
    turnInLabel: "return to relay shack mfer",
    required: 1,
    requiredQuestId: "cut-the-static",
    xpReward: 470,
    objectives: [
      { id: "static-baron-nox", label: "drop the Static Baron" },
    ],
    rewardItemIds: ["baron-breaker-board"],
    nextQuestId: "ogre-raid-daily",
  },
  "ogre-raid-daily": {
    title: "too much signal",
    giverNpcId: "beacon-keeper-mfer",
    description: "Once a day the relay can be pushed hard enough to call down something huge, loud, and fully unnecessary. That's your raid.",
    objectiveLabel: "drop too much signal",
    turnInLabel: "report back to relay shack mfer",
    required: 1,
    requiredQuestId: "baron-of-static",
    xpReward: 700,
    objectives: [
      { id: "raid-ogre-mfer", label: "drop too much signal" },
    ],
    repeatCooldownMs: 86_400_000,
    repeatLabel: "daily raid",
  },
} as const;

export const QUEST_IDS = Object.keys(QUESTS) as Array<keyof typeof QUESTS>;
