export const QUESTS = {
  "mfer-beginnings": {
    title: "First GM",
    giverNpcId: "og-mfer",
    description: "OG mfer wants to make sure you can check in with town before heading deeper into the plaza.",
    objectiveLabel: "Check back with OG mfer",
    turnInLabel: "Return to OG mfer",
    required: 1,
    autoReady: true,
    nextQuestId: "sealed-note",
  },
  "sealed-note": {
    title: "Sealed Note",
    giverNpcId: "og-mfer",
    turnInNpcId: "wearables-mfer",
    description: "OG mfer hands you a sealed note for Wearables mfer. No peeking.",
    objectiveLabel: "Deliver OG's sealed note",
    turnInLabel: "Bring the note to Wearables mfer",
    required: 1,
    requiredQuestId: "mfer-beginnings",
    startItemId: "sealed-note",
    requiredItemId: "sealed-note",
    consumeItem: true,
    nextQuestId: "farmhand-bandanas",
  },
  "farmhand-bandanas": {
    title: "Red-Eye Bandanas",
    giverNpcId: "wearables-mfer",
    description: "Wearables mfer can stitch warning flags if you bring scraps from the mad farmers.",
    objectiveLabel: "Collect farmhand bandanas",
    turnInLabel: "Return bandanas to Wearables mfer",
    required: 2,
    requiredQuestId: "sealed-note",
    requiredItemId: "farmhand-bandana",
    consumeItem: true,
    dropRate: 0.58,
  },
  "dao-tour": {
    title: "DAO Tour",
    giverNpcId: "dao-mfer",
    description: "DAO mfer wants you to find the hall and report back once you know where proposals will live.",
    objectiveLabel: "Check back with DAO mfer",
    turnInLabel: "Return to DAO mfer",
    required: 1,
    autoReady: true,
  },
  "fountain-vibes": {
    title: "Fountain Vibes",
    giverNpcId: "fountain-mfer",
    description: "Fountain mfer wants you to take a quick breather by the plaza fountain.",
    objectiveLabel: "Check back with Fountain mfer",
    turnInLabel: "Return to Fountain mfer",
    required: 1,
    autoReady: true,
  },
  "feral-farmers": {
    title: "Feral Farmers",
    giverNpcId: "hogwatch-mfer",
    description: "The busted farm is raising feral hogs that keep charging townspeople.",
    objectiveLabel: "Defeat Bran, Mae, and Sol",
    turnInLabel: "Return to Hogwatch mfer",
    required: 3,
    objectives: [
      { id: "farmhand-bran", label: "Defeat Farmhand Bran" },
      { id: "farmhand-mae", label: "Defeat Farmhand Mae" },
      { id: "field-mage-sol", label: "Defeat Field mage Sol" },
    ],
    nextQuestId: "hog-livers",
  },
  "hog-livers": {
    title: "Liver Remedy",
    giverNpcId: "hogwatch-mfer",
    description: "Hog livers can be brewed into a charm that keeps the worst hogs away from the plaza.",
    objectiveLabel: "Collect hog livers",
    turnInLabel: "Return to Hogwatch mfer",
    required: 5,
    requiredQuestId: "feral-farmers",
    requiredItemId: "hog-liver",
    consumeItem: true,
    dropRate: 0.66,
  },
} as const;

export const QUEST_IDS = Object.keys(QUESTS) as Array<keyof typeof QUESTS>;
