import {
  TRAIT_CHANGE_MFERGPT_AMOUNT_LABEL,
  TRAIT_CHANGE_MFERGPT_AMOUNT_WEI,
} from "./appearance.js";

export const RESPEC_MFER_NPC_ID = "respec-mfer";
export const TALENT_RESPEC_PRODUCT_ID = "talent-respec";
export const TALENT_RESPEC_MFERGPT_AMOUNT_WEI = TRAIT_CHANGE_MFERGPT_AMOUNT_WEI;
export const TALENT_RESPEC_MFERGPT_AMOUNT_LABEL = TRAIT_CHANGE_MFERGPT_AMOUNT_LABEL;
